#include "agent_indicator_model.hpp"
#include <QCoreApplication>
#include <QRectF>
#include <iostream>
#include <iomanip>
using namespace mokaid;
QRectF rectangle(AgentIndicatorModel &model,int row){auto i=model.index(row);return {model.data(i,AgentIndicatorModel::LabelX).toDouble(),model.data(i,AgentIndicatorModel::LabelY).toDouble(),model.data(i,AgentIndicatorModel::LabelWidth).toDouble(),model.data(i,AgentIndicatorModel::LabelHeight).toDouble()};}
QRectF lerp(QRectF a,QRectF b,double t){return {a.topLeft()+(b.topLeft()-a.topLeft())*t,a.size()+(b.size()-a.size())*t};}
void print(const char *label,QRectF a){std::cout<<label<<" x="<<a.x()<<" y="<<a.y()<<" width="<<a.width()<<" height="<<a.height()<<'\n';}
int main(int argc,char**argv){QCoreApplication app(argc,argv);AgentIndicatorModel model;engine::Frame frame;for(int i=0;i<9;++i)frame.actorIndicators.push_back({"id_"+std::to_string(i),"Agent "+std::to_string(i),"working",i+1,{0,0,0},0});QVector<QRectF>old;std::cout<<std::fixed<<std::setprecision(8);for(int step=0;step<3600;++step){const float time=float(step)/30;for(auto&a:frame.actorIndicators){float i=std::stof(a.id.substr(3));a.headWorld={.8F*std::sin(time*.06F)+.03F*std::sin(time+i),.83F*std::cos(time*.05F)+.025F*std::sin(time*.7F+i),0};}if(step%3==0)std::reverse(frame.actorIndicators.begin(),frame.actorIndicators.end());model.sync(frame,{700,600});QVector<QRectF>next;for(int i=0;i<9;++i){if(!model.data(model.index(i),AgentIndicatorModel::OnScreen).toBool())return 3;next.push_back(rectangle(model,i));for(int j=0;j<i;++j)if(next[i].intersects(next[j]))return 4;}if(old.size()==9)for(int sample=1;sample<100;++sample){double t=double(sample)/100;for(int i=0;i<9;++i)for(int j=0;j<i;++j){auto a=lerp(old[i],next[i],t),b=lerp(old[j],next[j],t);if(a.intersects(b)){std::cout<<"FIRST COLLISION viewport=700x600 frame="<<step<<" simulation_seconds="<<time<<" progress="<<t<<" pair=id_"<<i<<",id_"<<j<<'\n';print("oldA",old[i]);print("nextA",next[i]);print("oldB",old[j]);print("nextB",next[j]);print("interpolatedA",a);print("interpolatedB",b);print("intersection",a.intersected(b));std::cout<<"Both endpoint layouts verified non-overlapping.\n";return 0;}}}old=next;}std::cout<<"NO SAME-PROGRESS INTERPOLATION COLLISION in120s\n";return 1;}
