"""Full webapp scaffold (React + Next.js + TypeScript) for complex site missions.

`generate_website` still ships a polished one-file HTML preview that opens
instantly in the immersive viewer. This tool additionally writes a deployable
project skeleton (package.json, vercel/render/supabase config stubs + README)
so the user only has to click partner buttons and connect their accounts —
DevOps owns the real OAuth / infrastructure side.
"""

from __future__ import annotations

import json
from typing import Any

import structlog

from app.tools.registry import RunContext, tool
from app.tools.website import _slugify, generate_website

log = structlog.get_logger()

_DEPLOY_README = """# Deploy this MOKAID webapp

## Live preview (MOKAID)
Open the generated HTML file in the task Output panel — immersive preview,
no install required.

## Stack
- React + Next.js + TypeScript (scaffold)
- Static HTML fallback for instant hosting

## One-click partners
1. **Vercel** — https://vercel.com/new
   Create a project, upload this folder (or push to GitHub and import).
2. **Render** — https://dashboard.render.com/select-repo?type=static
   Static site: publish root or the `out/` folder after `npm run build`.
3. **Supabase** — https://supabase.com/dashboard/new
   Create a project, copy URL + anon key into `.env.local` (see example).

## Local
```bash
npm install
npm run dev
```

## Notes
- Real provider OAuth and automated provisioning are wired by your MOKAID
  DevOps track (secrets on the platform side). Product UX stops at partner
  redirects + ready-to-upload artifacts.
"""

_PACKAGE_JSON = {
    "name": "mokaid-webapp",
    "version": "0.1.0",
    "private": True,
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint",
    },
    "dependencies": {
        "next": "^15.1.0",
        "react": "^19.0.0",
        "react-dom": "^19.0.0",
    },
    "devDependencies": {
        "@types/node": "^22.10.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        "typescript": "^5.7.0",
    },
}

_TSCONFIG = {
    "compilerOptions": {
        "target": "ES2017",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": True,
        "skipLibCheck": True,
        "strict": True,
        "noEmit": True,
        "esModuleInterop": True,
        "module": "esnext",
        "moduleResolution": "bundler",
        "resolveJsonModule": True,
        "isolatedModules": True,
        "jsx": "preserve",
        "incremental": True,
        "plugins": [{"name": "next"}],
        "paths": {"@/*": ["./*"]},
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    "exclude": ["node_modules"],
}

_VERCEL_JSON = {"$schema": "https://openapi.vercel.sh/vercel.json", "framework": "nextjs"}

_RENDER_YAML = """services:
  - type: web
    name: mokaid-webapp
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
"""

_ENV_EXAMPLE = """# Supabase (create project → Project Settings → API)
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=

# Optional
# DATABASE_URL=
"""

_APP_PAGE = '''export default function Home() {
  return (
    <main style={{ fontFamily: "system-ui, sans-serif", padding: "4rem 1.5rem", maxWidth: 720, margin: "0 auto" }}>
      <p style={{ letterSpacing: "0.08em", textTransform: "uppercase", fontSize: 12, opacity: 0.6 }}>
        Generated with MOKAID
      </p>
      <h1 style={{ fontSize: "2.4rem", lineHeight: 1.15, margin: "0.4rem 0 1rem" }}>
        {brand}
      </h1>
      <p style={{ fontSize: "1.05rem", lineHeight: 1.6, opacity: 0.85 }}>
        Next.js + TypeScript scaffold. Open the static HTML deliverable for a
        full design preview, then deploy this folder to Vercel or Render and
        connect Supabase when you need a backend.
      </p>
    </main>
  );
}
'''

_LAYOUT = '''import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MOKAID Webapp",
  description: "Generated by MOKAID",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, background: "#0b0d12", color: "#f4f6fb" }}>{children}</body>
    </html>
  );
}
'''


@tool("generate_webapp")
async def generate_webapp(params: dict[str, Any], ctx: RunContext) -> Any:
    """Builds a React/Next.js/TypeScript webapp scaffold plus instant HTML preview
    and deploy-ready config (Vercel / Render / Supabase)."""
    brief = (
        params.get("brief")
        or params.get("instructions")
        or ctx.task_description
        or ctx.task_title
        or ""
    )
    brand = params.get("brand_name") or params.get("brand") or "App"
    style = params.get("style") or ""

    if not brief:
        return {"error": "No brief provided for the webapp."}

    # Phase 1 — premium HTML preview (same art pipeline as generate_website).
    site = await generate_website(
        {"brief": brief, "brand_name": brand, "style": style},
        ctx,
    )
    if isinstance(site, dict) and site.get("error"):
        return site

    slug = _slugify(brand or ctx.task_title or "webapp")
    pkg = dict(_PACKAGE_JSON)
    pkg["name"] = slug

    artifacts: list[dict[str, Any]] = []
    if isinstance(site, dict) and site.get("filename"):
        artifacts.append(
            {
                "filename": site["filename"],
                "drive_item_id": site.get("drive_item_id"),
                "kind": "preview_html",
            }
        )

    files: list[tuple[str, str, str]] = [
        (f"{slug}-package.json", json.dumps(pkg, indent=2) + "\n", "application/json"),
        (f"{slug}-tsconfig.json", json.dumps(_TSCONFIG, indent=2) + "\n", "application/json"),
        (f"{slug}-vercel.json", json.dumps(_VERCEL_JSON, indent=2) + "\n", "application/json"),
        (f"{slug}-render.yaml", _RENDER_YAML, "text/yaml"),
        (f"{slug}-env.example", _ENV_EXAMPLE, "text/plain"),
        (f"{slug}-DEPLOY.md", _DEPLOY_README, "text/markdown"),
        (
            f"{slug}-app-page.tsx",
            _APP_PAGE.replace("{brand}", brand.replace('"', '\\"')),
            "text/typescript",
        ),
        (f"{slug}-app-layout.tsx", _LAYOUT, "text/typescript"),
    ]

    if ctx.phoenix:
        for filename, body, mime in files:
            saved = await ctx.phoenix.save_task_output(
                ctx.workspace_id,
                ctx.task_id,
                filename,
                body,
                mime_type=mime,
            )
            if saved:
                artifacts.append(
                    {
                        "filename": filename,
                        "drive_item_id": saved.get("id") or saved.get("drive_item_id"),
                        "kind": "scaffold",
                    }
                )

    if not artifacts:
        return {"error": "Could not save the webapp scaffold."}

    log.info("webapp_generated", brand=brand, files=len(artifacts))
    return {
        "filename": site.get("filename") if isinstance(site, dict) else None,
        "drive_item_id": site.get("drive_item_id") if isinstance(site, dict) else None,
        "mime_type": "text/html",
        "artifacts": artifacts,
        "stack": "react-next-typescript",
        "deploy": {
            "vercel": "https://vercel.com/new",
            "render": "https://dashboard.render.com/select-repo?type=static",
            "supabase": "https://supabase.com/dashboard/new",
        },
        "note": (
            "HTML preview + Next.js scaffold ready. Open preview in MOKAID, "
            "then use Deploy buttons (Vercel / Render / Supabase)."
        ),
    }
