defmodule Mokaid.AI.Workers.ConverseWorker do
  @moduledoc """
  Conversational replies: when a teammate writes in a task thread while the
  assigned agent is NOT running, the agent still answers — the thread is a
  real conversation, not a log. The reply is generated by the AI worker
  (which posts it back as a task comment through the worker API).
  """

  use Oban.Worker, queue: :ai_dispatch, max_attempts: 2

  alias Mokaid.AI
  alias Mokaid.Tasks

  @impl Oban.Worker
  def perform(%Oban.Job{args: %{"workspace_id" => workspace_id, "task_id" => task_id}}) do
    config = Application.fetch_env!(:mokaid, :ai_worker)
    task = Tasks.get_task(workspace_id, task_id)

    cond do
      task == nil or task.assigned_agent_id == nil ->
        :ok

      # A live run already talks in the thread (ack, failure explanations);
      # don't have two voices at once.
      Tasks.active_runs_for_task(workspace_id, task_id) != [] ->
        :ok

      true ->
        payload = %{
          workspace_id: workspace_id,
          task_id: task_id,
          agent_id: task.assigned_agent_id,
          task_title: task.title,
          task_description: task.description,
          task_status: task.status,
          conversation: AI.default_input(task)["conversation"]
        }

        Mokaid.AI.WorkerClient.post(
          "/converse",
          Map.put(payload, :type, "converse"),
          config: config,
          soft: true
        )
    end
  end
end
