# Provider mocked end-to-end: no network, no secret access, no AWS mutations.
# Policy JSON is generated by the real module, not replaced by mocked documents.
mock_provider "aws" {
  mock_data "aws_caller_identity" {
    defaults = { account_id = "660601648321" }
  }
}

variables {
  github_oidc_provider_arn = "arn:aws:iam::660601648321:oidc-provider/token.actions.githubusercontent.com"
  github_repository       = "Yapio-Ltd/mokaid"
  macos_signing_secret_arn = "arn:aws:secretsmanager:il-central-1:660601648321:secret:mokaid/desktop/stable/macos-signing-8pPQkT"
}

run "exact_stable_identity_and_trust" {
  command = plan

  assert {
    condition     = aws_iam_role.signer.name == "mokaid-desktop-signing-stable" && aws_iam_role.signer.max_session_duration == 3600
    error_message = "Only the fixed stable signing role with a one-hour maximum session is supported."
  }
  assert {
    condition = jsondecode(aws_iam_role.signer.assume_role_policy) == jsondecode(jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Sid       = "ApprovedStableSigningJob"
        Effect    = "Allow"
        Action    = "sts:AssumeRoleWithWebIdentity"
        Principal = { Federated = var.github_oidc_provider_arn }
        Condition = { StringEquals = {
          "token.actions.githubusercontent.com:aud" = "sts.amazonaws.com"
          "token.actions.githubusercontent.com:sub" = "repo:Yapio-Ltd/mokaid:environment:desktop-signing-stable"
        } }
      }]
    }))
    error_message = "Trust must require both exact STS audience and stable environment subject, without wildcard or branch fallback."
  }
}

run "only_two_read_operations_on_one_secret" {
  command = plan

  assert {
    condition = jsondecode(aws_iam_role_policy.signer.policy) == jsondecode(jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Sid      = "ReadOnlyStableMacSigningIdentity"
        Effect   = "Allow"
        Action   = ["secretsmanager:DescribeSecret", "secretsmanager:GetSecretValue"]
        Resource = var.macos_signing_secret_arn
      }]
    }))
    error_message = "No additional secret, API, S3, publishing, KMS, PassRole, or mutation permission is allowed."
  }
}

run "required_ownership_tags_cannot_be_overridden" {
  command = plan
  variables { tags = { Channel = "beta", Project = "other", Ticket = "fixture" } }
  assert {
    condition     = aws_iam_role.signer.tags.Channel == "stable" && aws_iam_role.signer.tags.Project == "mokaid" && aws_iam_role.signer.tags.Ticket == "fixture"
    error_message = "Extra tags may not replace the stable signing identity."
  }
}

run "wildcard_secret_is_rejected" {
  command = plan
  variables { macos_signing_secret_arn = "arn:aws:secretsmanager:il-central-1:660601648321:secret:mokaid/desktop/stable/*" }
  expect_failures = [var.macos_signing_secret_arn]
}

run "beta_secret_is_rejected" {
  command = plan
  variables { macos_signing_secret_arn = "arn:aws:secretsmanager:il-central-1:660601648321:secret:mokaid/desktop/beta/macos-signing-8pPQkT" }
  expect_failures = [var.macos_signing_secret_arn]
}

run "application_secret_is_rejected" {
  command = plan
  variables { macos_signing_secret_arn = "arn:aws:secretsmanager:il-central-1:660601648321:secret:mokaid/prod/api-8pPQkT" }
  expect_failures = [var.macos_signing_secret_arn]
}

run "wrong_secret_region_is_rejected" {
  command = plan
  variables { macos_signing_secret_arn = "arn:aws:secretsmanager:us-east-1:660601648321:secret:mokaid/desktop/stable/macos-signing-8pPQkT" }
  expect_failures = [var.macos_signing_secret_arn]
}

run "cross_account_secret_is_rejected" {
  command = plan
  variables { macos_signing_secret_arn = "arn:aws:secretsmanager:il-central-1:123456789012:secret:mokaid/desktop/stable/macos-signing-8pPQkT" }
  expect_failures = [aws_iam_role.signer]
}

run "cross_account_oidc_is_rejected" {
  command = plan
  variables { github_oidc_provider_arn = "arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com" }
  expect_failures = [aws_iam_role.signer]
}

run "untrusted_oidc_provider_is_rejected" {
  command = plan
  variables { github_oidc_provider_arn = "arn:aws:iam::660601648321:oidc-provider/example.com" }
  expect_failures = [var.github_oidc_provider_arn]
}

run "wildcard_repository_is_rejected" {
  command = plan
  variables { github_repository = "Yapio-Ltd/*" }
  expect_failures = [var.github_repository]
}

run "injected_subject_is_rejected" {
  command = plan
  variables { github_repository = "Yapio-Ltd/mokaid:ref:refs/heads/prod" }
  expect_failures = [var.github_repository]
}
