/**
 * Lights + camera extracted from office.blend (Blender 5.2, Z-up)
 * and converted to glTF / Babylon Y-up: (x, y, z)_gltf = (x, z, -y)_blender.
 *
 * Positions are in RAW GLB local space (before OfficeScene centering).
 * Apply the same -centerX / -minY / -centerZ offset at runtime.
 *
 * Regenerated by: blender -b office.blend -P scripts/dump_blender_lights.py
 * + scripts in scratchpad (do not hand-edit numbers — re-extract).
 */

export type OfficeLightType = "POINT" | "AREA" | "SUN" | "SPOT";

export interface OfficeLightDef {
  name: string;
  type: OfficeLightType;
  /** Raw GLB / Y-up position (before scene centering). */
  position: { x: number; y: number; z: number };
  color: { r: number; g: number; b: number };
  /** Blender watts — convert with ENERGY_TO_INTENSITY_* factors. */
  energy: number;
  size?: number;
  sizeY?: number;
  /** Direction the area light faces (Y-up). */
  normal?: { x: number; y: number; z: number };
}

export interface OfficeCameraDef {
  position: { x: number; y: number; z: number };
  target: { x: number; y: number; z: number };
  /** Vertical FOV in radians (Babylon FreeCamera). */
  fovVertical: number;
  /** Horizontal FOV in radians (for reference). */
  fovHorizontal: number;
  lens: number;
  near: number;
  far: number;
}

/** Convert Blender wattage → Babylon PointLight intensity (calibrated vs render). */
export const ENERGY_TO_INTENSITY_POINT = 0.06;
/** Convert Blender wattage → Babylon intensity for overhead AREA approximations. */
export const ENERGY_TO_INTENSITY_AREA = 0.5;

export const OFFICE_WORLD = {
  color: { r: 0, g: 0, b: 0 },
  strength: 1,
} as const;

export const OFFICE_BLOOM = {
  // Artist asked to enable bloom in the web app (Eevee bloom was off in the file).
  threshold: 0.45,
  weight: 0.8,
  kernel: 96,
  scale: 0.6,
} as const;

export const OFFICE_CAMERA: OfficeCameraDef = {
  // Calibrated visually against the artist's Render_1.png (the viewport camera
  // stored in the .blend didn't match the render). Elevation ~22°, framed so
  // the office fills the canvas with minimal empty background.
  position: { x: 7.11, y: 6.96, z: 12.9 },
  // Target lowered (~4° downward tilt) so the office bottom edge stays in
  // frame and no empty background shows above the back walls.
  target: { x: -0.146, y: -0.44, z: -0.804 },
  fovVertical: 0.468,
  fovHorizontal: 0.801,
  lens: 85,
  near: 0.1,
  far: 500,
};

export const OFFICE_LIGHTS: OfficeLightDef[] = [
  {
    "name": "Area",
    "type": "AREA",
    "position": {
      "x": 5.888,
      "y": 2.862,
      "z": 0.12
    },
    "color": {
      "r": 0.223,
      "g": 0.124,
      "b": 1
    },
    "energy": 196,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.001",
    "type": "AREA",
    "position": {
      "x": 1.531,
      "y": 2.862,
      "z": -2.867
    },
    "color": {
      "r": 1,
      "g": 0.424,
      "b": 0.155
    },
    "energy": 113,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.002",
    "type": "AREA",
    "position": {
      "x": -1.593,
      "y": 2.862,
      "z": -3.656
    },
    "color": {
      "r": 1,
      "g": 0.358,
      "b": 0.947
    },
    "energy": 113,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.003",
    "type": "AREA",
    "position": {
      "x": -2.382,
      "y": 2.862,
      "z": -6.253
    },
    "color": {
      "r": 0.333,
      "g": 0.32,
      "b": 1
    },
    "energy": 113,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.004",
    "type": "AREA",
    "position": {
      "x": -1.494,
      "y": 2.862,
      "z": -0.696
    },
    "color": {
      "r": 1,
      "g": 0.389,
      "b": 0.295
    },
    "energy": 73,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.005",
    "type": "AREA",
    "position": {
      "x": -2.317,
      "y": 2.862,
      "z": 2.362
    },
    "color": {
      "r": 1,
      "g": 0.29,
      "b": 0.611
    },
    "energy": 73,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.006",
    "type": "AREA",
    "position": {
      "x": -5.44,
      "y": 2.862,
      "z": 0.981
    },
    "color": {
      "r": 1,
      "g": 0.29,
      "b": 0.611
    },
    "energy": 41,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.007",
    "type": "AREA",
    "position": {
      "x": -5.375,
      "y": 2.862,
      "z": -2.209
    },
    "color": {
      "r": 0.77,
      "g": 0.369,
      "b": 1
    },
    "energy": 37,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.008",
    "type": "AREA",
    "position": {
      "x": 0.314,
      "y": 2.862,
      "z": 3.677
    },
    "color": {
      "r": 1,
      "g": 0.554,
      "b": 0.281
    },
    "energy": 41,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.009",
    "type": "AREA",
    "position": {
      "x": 5.345,
      "y": 2.862,
      "z": -4.445
    },
    "color": {
      "r": 0.191,
      "g": 0.235,
      "b": 1
    },
    "energy": 124,
    "size": 1,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Area.010",
    "type": "AREA",
    "position": {
      "x": 4.139,
      "y": 2.862,
      "z": 3.011
    },
    "color": {
      "r": 1,
      "g": 0.352,
      "b": 0.233
    },
    "energy": 41,
    "size": 0.958,
    "sizeY": 1,
    "normal": {
      "x": 0,
      "y": -1,
      "z": 0
    }
  },
  {
    "name": "Point",
    "type": "POINT",
    "position": {
      "x": -3.915,
      "y": 0.923,
      "z": -6.242
    },
    "color": {
      "r": 1,
      "g": 0.578,
      "b": 0.004
    },
    "energy": 36
  },
  {
    "name": "Point.001",
    "type": "POINT",
    "position": {
      "x": -0.193,
      "y": 1.073,
      "z": 3.395
    },
    "color": {
      "r": 1,
      "g": 0.578,
      "b": 0.004
    },
    "energy": 46
  },
  {
    "name": "Point.002",
    "type": "POINT",
    "position": {
      "x": -2.627,
      "y": 1.091,
      "z": 2.599
    },
    "color": {
      "r": 1,
      "g": 0.436,
      "b": 0.003
    },
    "energy": 46
  },
  {
    "name": "Point.003",
    "type": "POINT",
    "position": {
      "x": 0.275,
      "y": 1.148,
      "z": 0.408
    },
    "color": {
      "r": 1,
      "g": 0.578,
      "b": 0.004
    },
    "energy": 46
  },
  {
    "name": "Point.004",
    "type": "POINT",
    "position": {
      "x": 2.638,
      "y": 1.071,
      "z": -2.604
    },
    "color": {
      "r": 1,
      "g": 0.578,
      "b": 0.004
    },
    "energy": 46
  },
  {
    "name": "Point.005",
    "type": "POINT",
    "position": {
      "x": -4.486,
      "y": 1.071,
      "z": -2.604
    },
    "color": {
      "r": 1,
      "g": 0.578,
      "b": 0.004
    },
    "energy": 46
  }
];
